name: Test workflow

on:
  workflow_dispatch:
    branches:
      - main
      - staging

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          BRANCH: ${{env.GITHUB_REF_NAME}}
        run: |
          echo ${{ github.ref }}
          echo "$BRANCH"

      - name: Main step
        run: echo main
        if: github.ref == 'refs/heads/main'
      
      - name: Staging step
        run: echo staging
        if: github.ref == 'refs/heads/staging'
